// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNpWxsbBkt0Z7UvsCr80A8t8Q4VzPAaAk',
    appId: '1:896557837272:web:2999b066e4588df56c20ad',
    messagingSenderId: '896557837272',
    projectId: 'quran-app-754e2',
    authDomain: 'quran-app-754e2.firebaseapp.com',
    storageBucket: 'quran-app-754e2.firebasestorage.app',
    measurementId: 'G-N79DRDYBK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4CLXnKzGyU7GO2fXtmL-O6M_t3Di26cc',
    appId: '1:896557837272:android:3fed4d86f0c26ae36c20ad',
    messagingSenderId: '896557837272',
    projectId: 'quran-app-754e2',
    storageBucket: 'quran-app-754e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwzvxfOdowk83AqQh7Fc-dLXdskqYBrU',
    appId: '1:896557837272:ios:be024dc0e4d2e8cd6c20ad',
    messagingSenderId: '896557837272',
    projectId: 'quran-app-754e2',
    storageBucket: 'quran-app-754e2.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwzvxfOdowk83AqQh7Fc-dLXdskqYBrU',
    appId: '1:896557837272:ios:be024dc0e4d2e8cd6c20ad',
    messagingSenderId: '896557837272',
    projectId: 'quran-app-754e2',
    storageBucket: 'quran-app-754e2.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNpWxsbBkt0Z7UvsCr80A8t8Q4VzPAaAk',
    appId: '1:896557837272:web:cb8a292fbca49c386c20ad',
    messagingSenderId: '896557837272',
    projectId: 'quran-app-754e2',
    authDomain: 'quran-app-754e2.firebaseapp.com',
    storageBucket: 'quran-app-754e2.firebasestorage.app',
    measurementId: 'G-PS7XWQLGNL',
  );
}
